### ISSUE TITLE
Bug on latest version

### ISSUE THREAD

**Issue by Abdelazeem777** [ricardoemerson/dart-data-class-tools#12]
What is the point of doing this?
You just lost the enhancements you added on the last commit!

```dart
final user = User(name: "Abdelazeem");
newUser = user.copyWith(name: null);
print(newUser.name); // OUTPUT => "Abdelazeem"
```
this is the old version with the issue of setting the item to null!

And it was fixed and working fine on the commit before this one!
by doing this:

```dart
final user = User(name: "Abdelazeem");
newUser = user.copyWith(name: () => null);
print(newUser.name); // OUTPUT => null
```
but now after this commit the output but will be like this

```dart
final user = User(name: "Abdelazeem");
newUser = user.copyWith(name: () => null);
print(newUser.name); // OUTPUT => "Abdelazeem"
```
So please revert this commit again 🙏🙏

**Comment by gmaggio** [comment]
@ricardoemerson:
FYI, this is related to "ValueGetter code simplification" related to https://github.com/ricardoemerson/dart-data-class-tools/pull/9.
The one who suggested the change noticed the bug and requested it be reverted: https://github.com/ricardoemerson/dart-data-class-tools/pull/11.

**Comment by Abdelazeem777** [comment]
@gmaggio 
I hope this commit reverted ASAP

**Comment by ricardoemerson** [comment]
Fixed. Thanks for feedback.
