### ISSUE TITLE
ValueGetter should not use in copyWIth

### ISSUE THREAD

**Issue by metaspook** [ricardoemerson/dart-data-class-tools#16]
As ValueGetter depands Flutter, and a Model must be in Pure Dart not depend on Flutter also in case of Bloc's state a Bloc/Cubit cannot depend on Flutter. It's breaks the pattern.
So please remove the ValueGetter from copyWith just use ?? to null check.
I hope u understand. Thanks in advance.

**Comment by x1z7** [comment]
The extension should declare it's own `ValueGetter` or `ValueGetter`-like type and use it instead of the framework one.
Not having this available makes generating `copyWith` unusable when having nullable props.

**Comment by ricardoemerson** [comment]
Just change the settings of extension to:

```json
{
  "dart-data-class-generator.copyWith.usesValueGetter": false,
}
```
